# -*- coding: utf-8 -*-
"""Day 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13UTC3jWYvKw5ldejMgLXZa1Oasa4Vvju
"""
import pandas as pd

df = pd.read_csv(r'C:\Users\Rafael Pietro\OneDrive\Cursos\DNC\Day 3\train.csv')

df

a=df.groupby(['Sex'])['PassengerId'].count().reset_index()
a

Homens=len(df[df['Sex']=='male'])
Mulheres = len(df[df['Sex']=='female'])

print(f'Haviam {Homens} homens e {Mulheres} mulheres a bordo, somando um total de {Homens+Mulheres} passageiros.')

totalTrip=len(df['PassengerId'])
mortos=len(df[df['Survived']==0])
percMortos= mortos/totalTrip

print(f'A percentagem de mortos foi de {percMortos*100:.2f}%.')

mask1=((df['Embarked']=='C')& (df['Survived']==1))
df['Flag_1']=0
df.loc[mask1,'Flag_1']=1

homensMortos=len(df[(df['Sex']=='male') & (df['Survived']==0)])
print(f"{homensMortos} Homens morreram.")

# df.loc[((df['Sex'] == 'male') & (df['Survived'] == 0))]

hMortos=((df['Sex']=='male') & (df['Survived']==0))

print(f"{len(df.loc[hMortos])} Homens morreram.")

adolescentes=len(df[(df['Age']<18)])

print(f"Haviam {adolescentes} adolescentes a bordo.")
df.loc[df['Age'] < 18].sort_values(by='Age',ascending=False)

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

hMortos=len(df[(df['Sex']=='male') & (df['Survived']==0)])
mMortos=len(df[(df['Sex']=='female') & (df['Survived']==0)])
print(hMortos,mMortos)

df[df['Survived']==0]

hMortos=len(df[(df['Sex']=='male') & (df['Survived']==0)])
mMortos=len(df[(df['Sex']=='female') & (df['Survived']==0)])
print(hMortos,mMortos)


df2=df[(df['Survived']==0)]
sns.set_theme(style="whitegrid")
ax=sns.countplot(x="Sex", data=df2)
plt.show()

